-- PROJECT: Northwind Traders Strategic Business Analysis
-- GOAL: Comprehensive KPI analysis for sales, retention, and logistics.
-- STACK: MySQL

-- List all orders along with the corresponding customer name and city
select o.orderID, c.customerID, c.companyName, c.city
from orders o join customers c on o.customerID = c.customerID;

-- Calculate the total quantity ordered for each product.
select p.productID, p.productName, sum(od.quantity) as Product_Quantity
from products p join order_details od on p.productID = od.productID
group by p.productID, p.productName
order by Product_Quantity desc;

-- Percentage of Total Revenue by Product
select p.productID, p.productName,
-- sum(od.unitPrice*od.quantity*(1-od.discount)) AS product_revenue,
(sum(od.unitPrice*od.quantity*(1-od.discount)) /
(select sum(od2.unitPrice*od2.quantity*(1-od2.discount)) as total_revenue from order_details od2))*100 as percentage_revenue
from products p join order_details od on p.productID = od.productID
group by p.productID, p.productName
order by percentage_revenue DESC;

-- Find the top 5 customers with the highest total spending on orders.
select o.customerID,
sum(od.quantity*od.unitPrice*(1-od.discount)) as Total_Spending
from orders o join order_details od on o.orderID = od.orderID
group by o.customerID
order by Total_Spending DESC
limit 5;

-- Update the discount of orders for discontinued products to zero.
update order_details
set discount = 0
where productID in
(select productID
from products
where discontinued = 1);

-- Calculate the average freight cost for each shipper and show only those with above-average costs.
select o.shipperID, avg(o.freight) as avg_freight
from orders o 
group by o.shipperID
having avg_freight > (select avg(orders.freight) from orders);

-- Find the monthly sales revenue generated by each employee.
select year(o.orderDate) as year_,Month(o.orderDate) as month_, o.employeeID, 
sum(od.quantity*od.unitPrice*(1 - od.discount)) monthly_sales
from orders o join order_details od on o.orderID= od.orderID
group by year_, month_, o.employeeID
order by year_, month_, o.employeeID;

-- Identify which shipping company handles the most orders where the total order value exceeds $500.
with above_500_orders as
	(select od.orderID, sum(od.quantity*od.unitPrice*(1 - od.discount)) as total_order_value
	from order_details od 
	group by od.orderID 
	having total_order_value>500)
select o.shipperID, count(*) as high_value_orders
from above_500_orders a5o join orders o on a5o.orderID = o.orderID
group by o.shipperID
order by high_value_orders desc;

-- Identify which employee has the highest sales (in terms of revenue) in each product category.
WITH cat_emp_sales AS (SELECT cat.categoryID, e.employeeID, e.employeeName,
SUM(od.quantity * od.unitPrice * (1 - od.discount)) AS total_sales,
RANK() OVER (PARTITION BY cat.categoryID ORDER BY SUM(od.quantity * od.unitPrice * (1 - od.discount)) DESC) as sales_rank
FROM categories cat
JOIN products p ON cat.categoryID = p.categoryID
JOIN order_details od ON p.productID = od.productID
JOIN orders o ON od.orderID = o.orderID
JOIN employees e ON o.employeeID = e.employeeID
GROUP BY cat.categoryID, e.employeeID, e.employeeName)
SELECT categoryID, employeeID, employeeName, total_sales
FROM cat_emp_sales
WHERE sales_rank = 1;

-- Identify how frequently customers return to buy again (CHURN ANALYSIS - Retention Metric/Customer Loyalty)
select customerID, orderID, orderDate,
lag(orderDate) over (partition by customerID order by orderDate) as previous_order_date,
DATEDIFF(orderDate, lag(orderDate) over (partition by customerID order by orderDate)) as days_since_last_order
from orders;

-- Calculate Month-over-Month (MoM) Growth Percentage (BUSINESS PERFORMANCE - Growth Metric/Tracking)
with monthly_revenue as(
select date_format(o.orderDate, '%Y-%m') as order_month,
round(sum(od.unitPrice*od.quantity*(1-od.discount)),2) as current_month_revenue
from orders o join order_details od on o.orderID = od.orderID
group by order_month)
select order_month, current_month_revenue,
lag(current_month_revenue) over (order by order_month) as previous_month_revenue,
round(((current_month_revenue - lag(current_month_revenue) over (order by order_month))
/lag(current_month_revenue) over (order by order_month))*100,2) as growth_percentage
from monthly_revenue;

-- Find the top 3 selling products in every category. (INVENTORY FOCUS - Product Metric/Strategic Ranking)
with Ranked_Products as(
select c.categoryName, p.productName, sum(od.quantity) as total_quantity,
round(sum(od.unitPrice*od.quantity*(1-od.discount)),2) AS total_revenue,
dense_rank() over (partition by c.categoryName Order by sum(od.quantity) DESC) AS product_rank
from products p join order_details od on p.productID = od.productID
join categories c on p.categoryID = c.categoryID
group by c.categoryName, p.productName)
select * from Ranked_Products
where product_rank <= 3
order by categoryName, product_rank;

-- Create a running total of revenue ordered by date. (CASH FLOW - Finance Metric/Health (Cumulative Revenue))
with daily_sales as (select 
o.orderDate, 
sum(od.unitPrice*od.quantity*(1-od.discount)) as daily_revenue
from order_details od join orders o on od.orderID = o.orderID
group by o.orderDate)
select orderDate,
daily_revenue,
sum(daily_revenue) over (order by orderDate) as running_total
from daily_sales
